export const LOAD_PUBLIC_ASSETS = "LOAD_PUBLIC_ASSETS";
export const PUBLIC_ASSETS_LOADED = "PUBLIC_ASSETS_LOADED";
export const LOADING_PUBLIC_ASSETS_FAILED = "LOADING_PUBLIC_ASSETS_FAILED";

export const ADD_NEW_PUBLIC_ASSET = "ADD_NEW_PUBLIC_ASSET";
export const NEW_PUBLIC_ASSET_ADDED = "NEW_PUBLIC_ASSET_ADDED";
export const ADDING_NEW_PUBLIC_ASSET_FAILED = "ADDING_NEW_PUBLIC_ASSET_FAILED";


