const ADD_CAMPAIGN_TEMPLATE = "ADD_CAMPAIGN_TEMPLATE";
const ADD_CAMPAIGN_TEMPLATE_SUCCESS = "ADD_CAMPAIGN_TEMPLATE_SUCCESS";
const ADD_CAMPAIGN_TEMPLATE_FAILURE = "ADD_CAMPAIGN_TEMPLATE_FAILURE";

const GET_TEMPLATES = "GET_TEMPLATES";
const GET_TEMPLATES_SUCCESS = "GET_TEMPLATES_SUCCESS";
const GET_TEMPLATES_FAILURE = "GET_TEMPLATES_FAILURE";

export default {
  ADD_CAMPAIGN_TEMPLATE,
  ADD_CAMPAIGN_TEMPLATE_SUCCESS,
  ADD_CAMPAIGN_TEMPLATE_FAILURE,
  GET_TEMPLATES,
  GET_TEMPLATES_SUCCESS,
  GET_TEMPLATES_FAILURE
};
